basePath: /admin
definitions:
  admin.login:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  config.RedisConf:
    properties:
      addr:
        description: redis address
        type: string
      mode:
        description: redis mode (cluster/standalone)
        type: string
      password:
        description: password for login redis
        type: string
      username:
        description: username for login redis
        type: string
    type: object
host: localhost:8086
info:
  contact:
    email: pingfan14@gmail.com
    name: sinux
    url: https://github.com/sinuxlee/giny
  description: API Admin for Giny
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
  termsOfService: https://github.com/sinuxlee/giny
  title: Giny API Admin
  version: "1.0"
paths:
  /api/redis:
    get:
      consumes:
      - application/json
      description: |-
        Get Redis Config from KV Store
        config contains: mode(cluster/standalone), address, username, password
      produces:
      - application/json
      responses:
        "200":
          description: 响应体
          schema:
            allOf:
            - type: object
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/config.RedisConf'
                msg:
                  type: string
              type: object
      summary: Get Redis Config from KV Store
      tags:
      - Redis
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login Admin, the API will return Token
      parameters:
      - description: name and pass
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/admin.login'
      produces:
      - application/json
      responses:
        "200":
          description: HTTP Response
          schema:
            allOf:
            - type: object
            - properties:
                code:
                  type: integer
                data:
                  allOf:
                  - type: object
                  - properties:
                      expireAt:
                        type: integer
                      token:
                        type: string
                    type: object
                msg:
                  type: string
              type: object
      summary: Login Giny API Admin
      tags:
      - User
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout Admin, let client reset cookie
      produces:
      - application/json
      responses:
        "200":
          description: HTTP Response
          schema:
            allOf:
            - type: object
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
      summary: Logout Giny API Admin
      tags:
      - User
  /auth/refresh-token:
    get:
      consumes:
      - application/json
      description: return new token
      produces:
      - application/json
      responses:
        "200":
          description: HTTP Response
          schema:
            allOf:
            - type: object
            - properties:
                code:
                  type: integer
                data:
                  allOf:
                  - type: object
                  - properties:
                      expireAt:
                        type: integer
                      token:
                        type: string
                    type: object
                msg:
                  type: string
              type: object
      summary: Refresh Token
      tags:
      - User
schemes:
- http
securityDefinitions:
  BasicAuth:
    type: basic
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Some APIs to operate Key and Value in Store
  name: admin
x-extension-openapi:
  example: value on a json format
