name: build giny
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.18', '1.19' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go Env
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        env:
          GO111MODULE: on

      - name: Unit Test
        run: go test ./...

      - name: Build
        run: go build -o giny ./cmd/giny/*
